<script type='text/javascript'>//<![CDATA[
(function(a){a.fn.lazyload=function(b){var c={threshold:0,failurelimit:0,event:"scroll",effect:"show",container:window};if(b){a.extend(c,b)}var d=this;if("scroll"==c.event){a(c.container).bind("scroll",function(b){var e=0;d.each(function(){if(a.abovethetop(this,c)||a.leftofbegin(this,c)){}else if(!a.belowthefold(this,c)&&!a.rightoffold(this,c)){a(this).trigger("appear")}else{if(e++>c.failurelimit){return false}}});var f=a.grep(d,function(a){return!a.loaded});d=a(f)})}this.each(function(){var b=this;if(undefined==a(b).attr("original")){a(b).attr("original",a(b).attr("src"))}if("scroll"!=c.event||undefined==a(b).attr("src")||c.placeholder==a(b).attr("src")||a.abovethetop(b,c)||a.leftofbegin(b,c)||a.belowthefold(b,c)||a.rightoffold(b,c)){if(c.placeholder){a(b).attr("src",c.placeholder)}else{a(b).removeAttr("src")}b.loaded=false}else{b.loaded=true}a(b).one("appear",function(){if(!this.loaded){a("<img />").bind("load",function(){a(b).hide().attr("src",a(b).attr("original"))[c.effect](c.effectspeed);b.loaded=true}).attr("src",a(b).attr("original"))}});if("scroll"!=c.event){a(b).bind(c.event,function(c){if(!b.loaded){a(b).trigger("appear")}})}});a(c.container).trigger(c.event);return this};a.belowthefold=function(b,c){if(c.container===undefined||c.container===window){var d=a(window).height()+a(window).scrollTop()}else{var d=a(c.container).offset().top+a(c.container).height()}return d<=a(b).offset().top-c.threshold};a.rightoffold=function(b,c){if(c.container===undefined||c.container===window){var d=a(window).width()+a(window).scrollLeft()}else{var d=a(c.container).offset().left+a(c.container).width()}return d<=a(b).offset().left-c.threshold};a.abovethetop=function(b,c){if(c.container===undefined||c.container===window){var d=a(window).scrollTop()}else{var d=a(c.container).offset().top}return d>=a(b).offset().top+c.threshold+a(b).height()};a.leftofbegin=function(b,c){if(c.container===undefined||c.container===window){var d=a(window).scrollLeft()}else{var d=a(c.container).offset().left}return d>=a(b).offset().left+c.threshold+a(b).width()};a.extend(a.expr[":"],{"below-the-fold":"$.belowthefold(a, {threshold : 0, container: window})","above-the-fold":"!$.belowthefold(a, {threshold : 0, container: window})","right-of-fold":"$.rightoffold(a, {threshold : 0, container: window})","left-of-fold":"!$.rightoffold(a, {threshold : 0, container: window})"})})(jQuery);$(function(){$("img").lazyload({placeholder:"http://i22.servimg.com/u/f22/15/42/72/40/grey10.gif",effect:"fadeIn",threshold:"-50"})})//]]></script>

function createPostSummary(c,d,b,a){var e=document,g=configSummary;c=e.getElementById(c).value;d=e.getElementById(d);d.innerHTML=c;e=d.getElementsByTagName("img");var h=d.getElementsByTagName("iframe");e=0===e.length&&0===h.length?g.BackupImage:0===e.length&&0<h.length?"https://img.youtube.com/vi/"+h[0].src.match(/(\?v=|&v=|\/\d\/|\/embed\/|\/v\/|\.be\/)([a-zA-Z0-9\-_]+)/)[2]+"/0.jpg":e[0].src.replace(/\/s[0-9]+(\-c)?\//,"/s"+g.thumbnailSize+"-c/");c=c.replace(/<(.*?)>/g,"").replace(/[\n\r]+/g," ");
d.innerHTML='<a class="thumbimgx" title="'+b+'" href="'+a+'"><img class="post-thumbnail" src="'+e+'" alt="thumbnail" width="'+g.thumbnailSize+'" height="'+g.thumbnailSize+'"></a><strong><a class="titlex" href="'+a+'">'+b+"</a></strong><p>"+c.substring(0,g.summaryLength)+"&hellip;</p>"}jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(c,d,b,a,e){return jQuery.easing[jQuery.easing.def](c,d,b,a,e)},easeInQuad:function(c,d,b,a,e){return a*(d/=e)*d+b},easeOutQuad:function(c,d,b,a,e){return-a*(d/=e)*(d-2)+b},easeInOutQuad:function(c,d,b,a,e){return 1>(d/=e/2)?a/2*d*d+b:-a/2*(--d*(d-2)-1)+b},easeInCubic:function(c,d,b,a,e){return a*(d/=e)*d*d+b},easeOutCubic:function(c,d,b,a,e){return a*((d=d/e-1)*d*d+1)+b},easeInOutCubic:function(c,d,b,a,e){return 1>(d/=e/2)?a/2*d*d*d+b:
a/2*((d-=2)*d*d+2)+b},easeInQuart:function(c,d,b,a,e){return a*(d/=e)*d*d*d+b},easeOutQuart:function(c,d,b,a,e){return-a*((d=d/e-1)*d*d*d-1)+b},easeInOutQuart:function(c,d,b,a,e){return 1>(d/=e/2)?a/2*d*d*d*d+b:-a/2*((d-=2)*d*d*d-2)+b},easeInQuint:function(c,d,b,a,e){return a*(d/=e)*d*d*d*d+b},easeOutQuint:function(c,d,b,a,e){return a*((d=d/e-1)*d*d*d*d+1)+b},easeInOutQuint:function(c,d,b,a,e){return 1>(d/=e/2)?a/2*d*d*d*d*d+b:a/2*((d-=2)*d*d*d*d+2)+b},easeInSine:function(c,d,b,a,e){return-a*Math.cos(d/
e*(Math.PI/2))+a+b},easeOutSine:function(c,d,b,a,e){return a*Math.sin(d/e*(Math.PI/2))+b},easeInOutSine:function(c,d,b,a,e){return-a/2*(Math.cos(Math.PI*d/e)-1)+b},easeInExpo:function(c,d,b,a,e){return 0==d?b:a*Math.pow(2,10*(d/e-1))+b},easeOutExpo:function(c,d,b,a,e){return d==e?b+a:a*(-Math.pow(2,-10*d/e)+1)+b},easeInOutExpo:function(c,d,b,a,e){return 0==d?b:d==e?b+a:1>(d/=e/2)?a/2*Math.pow(2,10*(d-1))+b:a/2*(-Math.pow(2,-10*--d)+2)+b},easeInCirc:function(c,d,b,a,e){return-a*(Math.sqrt(1-(d/=e)*
d)-1)+b},easeOutCirc:function(c,d,b,a,e){return a*Math.sqrt(1-(d=d/e-1)*d)+b},easeInOutCirc:function(c,d,b,a,e){return 1>(d/=e/2)?-a/2*(Math.sqrt(1-d*d)-1)+b:a/2*(Math.sqrt(1-(d-=2)*d)+1)+b},easeInElastic:function(c,d,b,a,e){c=0;var g=a;if(0==d)return b;if(1==(d/=e))return b+a;c||(c=.3*e);g<Math.abs(a)?(g=a,a=c/4):a=c/(2*Math.PI)*Math.asin(a/g);return-(g*Math.pow(2,10*--d)*Math.sin(2*(d*e-a)*Math.PI/c))+b},easeOutElastic:function(c,d,b,a,e){var g=0,h=a;if(0==d)return b;if(1==(d/=e))return b+a;g||
(g=.3*e);h<Math.abs(a)?(h=a,c=g/4):c=g/(2*Math.PI)*Math.asin(a/h);return h*Math.pow(2,-10*d)*Math.sin(2*(d*e-c)*Math.PI/g)+a+b},easeInOutElastic:function(c,d,b,a,e){var g=0,h=a;if(0==d)return b;if(2==(d/=e/2))return b+a;g||(g=.3*e*1.5);h<Math.abs(a)?(h=a,c=g/4):c=g/(2*Math.PI)*Math.asin(a/h);return 1>d?-.5*h*Math.pow(2,10*--d)*Math.sin(2*(d*e-c)*Math.PI/g)+b:h*Math.pow(2,-10*--d)*Math.sin(2*(d*e-c)*Math.PI/g)*.5+a+b},easeInBack:function(c,d,b,a,e,g){void 0==g&&(g=1.70158);return a*(d/=e)*d*((g+1)*
d-g)+b},easeOutBack:function(c,d,b,a,e,g){void 0==g&&(g=1.70158);return a*((d=d/e-1)*d*((g+1)*d+g)+1)+b},easeInOutBack:function(c,d,b,a,e,g){void 0==g&&(g=1.70158);return 1>(d/=e/2)?a/2*d*d*(((g*=1.525)+1)*d-g)+b:a/2*((d-=2)*d*(((g*=1.525)+1)*d+g)+2)+b},easeInBounce:function(c,d,b,a,e){return a-jQuery.easing.easeOutBounce(c,e-d,0,a,e)+b},easeOutBounce:function(c,d,b,a,e){return(d/=e)<1/2.75?7.5625*a*d*d+b:d<2/2.75?a*(7.5625*(d-=1.5/2.75)*d+.75)+b:d<2.5/2.75?a*(7.5625*(d-=2.25/2.75)*d+.9375)+b:a*(7.5625*
(d-=2.625/2.75)*d+.984375)+b},easeInOutBounce:function(c,d,b,a,e){return d<e/2?.5*jQuery.easing.easeInBounce(c,2*d,0,a,e)+b:.5*jQuery.easing.easeOutBounce(c,2*d-e,0,a,e)+.5*a+b}});
(function(c){c.fn.hoverIntent=function(d,b,a){var e={interval:100,sensitivity:7,timeout:0};e="object"===typeof d?c.extend(e,d):c.isFunction(b)?c.extend(e,{over:d,out:b,selector:a}):c.extend(e,{over:d,out:d,selector:b});var g,h,m,l,p=function(a){g=a.pageX;h=a.pageY},n=function(a,b){b.hoverIntent_t=clearTimeout(b.hoverIntent_t);if(Math.abs(m-g)+Math.abs(l-h)<e.sensitivity)return c(b).off("mousemove.hoverIntent",p),b.hoverIntent_s=1,e.over.apply(b,[a]);m=g;l=h;b.hoverIntent_t=setTimeout(function(){n(a,
b)},e.interval)};d=function(a){var b=jQuery.extend({},a),d=this;d.hoverIntent_t&&(d.hoverIntent_t=clearTimeout(d.hoverIntent_t));"mouseenter"==a.type?(m=b.pageX,l=b.pageY,c(d).on("mousemove.hoverIntent",p),1!=d.hoverIntent_s&&(d.hoverIntent_t=setTimeout(function(){n(b,d)},e.interval))):(c(d).off("mousemove.hoverIntent",p),1==d.hoverIntent_s&&(d.hoverIntent_t=setTimeout(function(){d.hoverIntent_t=clearTimeout(d.hoverIntent_t);d.hoverIntent_s=0;e.out.apply(d,[b])},e.timeout)))};return this.on({"mouseenter.hoverIntent":d,
"mouseleave.hoverIntent":d},e.selector)}})(jQuery);
(function(c){var d=function(){var b=/iPhone|iPad|iPod/i.test(navigator.userAgent),a=function(){var a=document.documentElement.style;return"behavior"in a&&"fill"in a&&/iemobile/i.test(navigator.userAgent)}();(function(){b&&c(window).load(function(){c("body").children().on("click",c.noop)})})();var d=function(a,c){var b="sf-js-enabled";c.cssArrows&&(b+=" sf-arrows");a.toggleClass(b)},g=function(a,b){return a.find("li."+b.pathClass).slice(0,b.pathLevels).addClass(b.hoverClass+" sf-breadcrumb").filter(function(){return c(this).children("ul").hide().show().length}).removeClass(b.pathClass)},
h=function(a){var c=a.css("ms-touch-action");a.css("ms-touch-action","pan-y"===c?"auto":"pan-y")},m=function(a){var b=c(this),f=b.siblings("ul");0<f.length&&f.is(":hidden")&&(b.one("click.superfish",!1),"MSPointerDown"===a.type?b.trigger("focus"):c.proxy(l,b.parent("li"))())},l=function(){var a=c(this),b=r(a);clearTimeout(b.sfTimer);a.siblings().superfish("hide").end().superfish("show")},p=function(){var a=c(this),d=r(a);b?c.proxy(n,a,d)():(clearTimeout(d.sfTimer),d.sfTimer=setTimeout(c.proxy(n,a,
d),d.delay))},n=function(a){a.retainPath=-1<c.inArray(this[0],a.$path);this.superfish("hide");this.parents("."+a.hoverClass).length||(a.onIdle.call(this.closest(".sf-js-enabled")),a.$path.length&&c.proxy(l,a.$path)())},r=function(a){return a.closest(".sf-js-enabled").data("sf-options")};return{hide:function(a){if(this.length){var b=r(this);if(!b)return this;var f=!0===b.retainPath?b.$path:"";f=this.find("li."+b.hoverClass).add(this).not(f).removeClass(b.hoverClass).children("ul");var d=b.speedOut;
a&&(f.show(),d=0);b.retainPath=!1;b.onBeforeHide.call(f);f.stop(!0,!0).animate(b.animationOut,d,function(){var a=c(this);b.onHide.call(a)})}return this},show:function(){var a=r(this);if(!a)return this;var c=this.addClass(a.hoverClass).children("ul");a.onBeforeShow.call(c);c.stop(!0,!0).animate(a.animation,a.speed,function(){a.onShow.call(c)});return this},destroy:function(){return this.each(function(){var a=c(this),b=a.data("sf-options"),f=a.find("li:has(ul)");if(!b)return!1;clearTimeout(b.sfTimer);
d(a,b);f.children("a").toggleClass("sf-with-ul");h(a);a.off(".superfish").off(".hoverIntent");f.children("ul").attr("style",function(a,b){return b.replace(/display[^;]+;?/g,"")});b.$path.removeClass(b.hoverClass+" sf-breadcrumb").addClass(b.pathClass);a.find("."+b.hoverClass).removeClass(b.hoverClass);b.onDestroy.call(a);a.removeData("sf-options")})},init:function(e){return this.each(function(){var k=c(this);if(k.data("sf-options"))return!1;var f=c.extend({},c.fn.superfish.defaults,e),t=k.find("li:has(ul)");
f.$path=g(k,f);k.data("sf-options",f);d(k,f);t.children("a").toggleClass("sf-with-ul");h(k);if(c.fn.hoverIntent&&!f.disableHI)k.hoverIntent(l,p,"li:has(ul)");else k.on("mouseenter.superfish","li:has(ul)",l).on("mouseleave.superfish","li:has(ul)",p);var n="MSPointerDown.superfish";b||(n+=" touchend.superfish");a&&(n+=" mousedown.superfish");k.on("focusin.superfish","li",l).on("focusout.superfish","li",p).on(n,"a",m);t.not(".sf-breadcrumb").superfish("hide",!0);f.onInit.call(this)})}}}();c.fn.superfish=
function(b,a){return d[b]?d[b].apply(this,Array.prototype.slice.call(arguments,1)):"object"!==typeof b&&b?c.error("Method "+b+" does not exist on jQuery.fn.superfish"):d.init.apply(this,arguments)};c.fn.superfish.defaults={hoverClass:"sfHover",pathClass:"overrideThisToUse",pathLevels:1,delay:800,animation:{opacity:"show"},animationOut:{opacity:"hide"},speed:"normal",speedOut:"fast",cssArrows:!0,disableHI:!1,onInit:c.noop,onBeforeShow:c.noop,onShow:c.noop,onBeforeHide:c.noop,onHide:c.noop,onIdle:c.noop,
onDestroy:c.noop};c.fn.extend({hideSuperfishUl:d.hide,showSuperfishUl:d.show})})(jQuery);
(function(c){function d(a){var b=a||window.event,d=[].slice.call(arguments,1),e=0,l=0;a=c.event.fix(b);a.type="mousewheel";b.wheelDelta&&(e=b.wheelDelta/120);b.detail&&(e=-b.detail/3);var p=e;void 0!==b.axis&&b.axis===b.HORIZONTAL_AXIS&&(p=0,l=-1*e);void 0!==b.wheelDeltaY&&(p=b.wheelDeltaY/120);void 0!==b.wheelDeltaX&&(l=-1*b.wheelDeltaX/120);d.unshift(a,e,l,p);return(c.event.dispatch||c.event.handle).apply(this,d)}var b=["DOMMouseScroll","mousewheel"];if(c.event.fixHooks)for(var a=b.length;a;)c.event.fixHooks[b[--a]]=
c.event.mouseHooks;c.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=b.length;a;)this.addEventListener(b[--a],d,!1);else this.onmousewheel=d},teardown:function(){if(this.removeEventListener)for(var a=b.length;a;)this.removeEventListener(b[--a],d,!1);else this.onmousewheel=null}};c.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
(function(c){c.flexslider=function(d,b){var a=c(d),e=c.extend({},c.flexslider.defaults,b),g=e.namespace,h="ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,m=h?"touchend":"click",l="vertical"===e.direction,p=e.reverse,n=0<e.itemWidth,r="fade"===e.animation,q=""!==e.asNavFor,k={};c.data(d,"flexslider",a);k={init:function(){a.animating=!1;a.currentSlide=e.startAt;a.animatingTo=a.currentSlide;a.atEnd=0===a.currentSlide||a.currentSlide===a.last;a.containerSelector=e.selector.substr(0,
e.selector.search(" "));a.slides=c(e.selector,a);a.container=c(a.containerSelector,a);a.count=a.slides.length;a.syncExists=0<c(e.sync).length;"slide"===e.animation&&(e.animation="swing");a.prop=l?"top":"marginLeft";a.args={};a.manualPause=!1;var b;if(b=!e.video)if(b=!r)if(b=e.useCSS)a:{b=document.createElement("div");var d=["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"],g;for(g in d)if(void 0!==b.style[d[g]]){a.pfx=d[g].replace("Perspective","").toLowerCase();
a.prop="-"+a.pfx+"-transform";b=!0;break a}b=!1}a.transitions=b;""!==e.controlsContainer&&(a.controlsContainer=0<c(e.controlsContainer).length&&c(e.controlsContainer));""!==e.manualControls&&(a.manualControls=0<c(e.manualControls).length&&c(e.manualControls));e.randomize&&(a.slides.sort(function(){return Math.round(Math.random())-.5}),a.container.empty().append(a.slides));a.doMath();q&&k.asNav.setup();a.setup("init");e.controlNav&&k.controlNav.setup();e.directionNav&&k.directionNav.setup();e.keyboard&&
(1===c(a.containerSelector).length||e.multipleKeyboard)&&c(document).bind("keyup",function(b){b=b.keyCode;a.animating||39!==b&&37!==b||(b=39===b?a.getTarget("next"):37===b?a.getTarget("prev"):!1,a.flexAnimate(b,e.pauseOnAction))});e.mousewheel&&a.bind("mousewheel",function(b,c){b.preventDefault();var d=0>c?a.getTarget("next"):a.getTarget("prev");a.flexAnimate(d,e.pauseOnAction)});e.pausePlay&&k.pausePlay.setup();e.slideshow&&(e.pauseOnHover&&a.hover(function(){a.manualPlay||a.manualPause||a.pause()},
function(){a.manualPause||a.manualPlay||a.play()}),0<e.initDelay?setTimeout(a.play,e.initDelay):a.play());h&&e.touch&&k.touch();(!r||r&&e.smoothHeight)&&c(window).bind("resize focus",k.resize);setTimeout(function(){e.start(a)},200)},asNav:{setup:function(){a.asNav=!0;a.animatingTo=Math.floor(a.currentSlide/a.move);a.currentItem=a.currentSlide;a.slides.removeClass(g+"active-slide").eq(a.currentItem).addClass(g+"active-slide");a.slides.click(function(b){b.preventDefault();b=c(this);var d=b.index();
c(e.asNavFor).data("flexslider").animating||b.hasClass("active")||(a.direction=a.currentItem<d?"next":"prev",a.flexAnimate(d,e.pauseOnAction,!1,!0,!0))})}},controlNav:{setup:function(){a.manualControls?k.controlNav.setupManual():k.controlNav.setupPaging()},setupPaging:function(){var b=1;a.controlNavScaffold=c('<ol class="'+g+"control-nav "+g+("thumbnails"===e.controlNav?"control-thumbs":"control-paging")+'"></ol>');if(1<a.pagingCount)for(var d=0;d<a.pagingCount;d++){var p="thumbnails"===e.controlNav?
'<img src="'+a.slides.eq(d).attr("data-thumb")+'"/>':"<a>"+b+"</a>";a.controlNavScaffold.append("<li>"+p+"</li>");b++}a.controlsContainer?c(a.controlsContainer).append(a.controlNavScaffold):a.append(a.controlNavScaffold);k.controlNav.set();k.controlNav.active();a.controlNavScaffold.delegate("a, img",m,function(b){b.preventDefault();b=c(this);var d=a.controlNav.index(b);b.hasClass(g+"active")||(a.direction=d>a.currentSlide?"next":"prev",a.flexAnimate(d,e.pauseOnAction))});h&&a.controlNavScaffold.delegate("a",
"click touchstart",function(a){a.preventDefault()})},setupManual:function(){a.controlNav=a.manualControls;k.controlNav.active();a.controlNav.live(m,function(b){b.preventDefault();b=c(this);var d=a.controlNav.index(b);b.hasClass(g+"active")||(d>a.currentSlide?a.direction="next":a.direction="prev",a.flexAnimate(d,e.pauseOnAction))});h&&a.controlNav.live("click touchstart",function(a){a.preventDefault()})},set:function(){a.controlNav=c("."+g+"control-nav li "+("thumbnails"===e.controlNav?"img":"a"),
a.controlsContainer?a.controlsContainer:a)},active:function(){a.controlNav.removeClass(g+"active").eq(a.animatingTo).addClass(g+"active")},update:function(b,d){1<a.pagingCount&&"add"===b?a.controlNavScaffold.append(c("<li><a>"+a.count+"</a></li>")):1===a.pagingCount?a.controlNavScaffold.find("li").remove():a.controlNav.eq(d).closest("li").remove();k.controlNav.set();1<a.pagingCount&&a.pagingCount!==a.controlNav.length?a.update(d,b):k.controlNav.active()}},directionNav:{setup:function(){var b=c('<ul class="'+
g+'direction-nav"><li><a class="'+g+'prev" href="#">'+e.prevText+'</a></li><li><a class="'+g+'next" href="#">'+e.nextText+"</a></li></ul>");a.controlsContainer?(c(a.controlsContainer).append(b),a.directionNav=c("."+g+"direction-nav li a",a.controlsContainer)):(a.append(b),a.directionNav=c("."+g+"direction-nav li a",a));k.directionNav.update();a.directionNav.bind(m,function(b){b.preventDefault();b=c(this).hasClass(g+"next")?a.getTarget("next"):a.getTarget("prev");a.flexAnimate(b,e.pauseOnAction)});
h&&a.directionNav.bind("click touchstart",function(a){a.preventDefault()})},update:function(){var b=g+"disabled";1===a.pagingCount?a.directionNav.addClass(b):e.animationLoop?a.directionNav.removeClass(b):0===a.animatingTo?a.directionNav.removeClass(b).filter("."+g+"prev").addClass(b):a.animatingTo===a.last?a.directionNav.removeClass(b).filter("."+g+"next").addClass(b):a.directionNav.removeClass(b)}},pausePlay:{setup:function(){var b=c('<div class="'+g+'pauseplay"><a></a></div>');a.controlsContainer?
(a.controlsContainer.append(b),a.pausePlay=c("."+g+"pauseplay a",a.controlsContainer)):(a.append(b),a.pausePlay=c("."+g+"pauseplay a",a));k.pausePlay.update(e.slideshow?g+"pause":g+"play");a.pausePlay.bind(m,function(b){b.preventDefault();c(this).hasClass(g+"pause")?(a.manualPause=!0,a.manualPlay=!1,a.pause()):(a.manualPause=!1,a.manualPlay=!0,a.play())});h&&a.pausePlay.bind("click touchstart",function(a){a.preventDefault()})},update:function(b){"play"===b?a.pausePlay.removeClass(g+"pause").addClass(g+
"play").text(e.playText):a.pausePlay.removeClass(g+"play").addClass(g+"pause").text(e.pauseText)}},touch:function(){function b(b){q=l?h-b.touches[0].pageY:h-b.touches[0].pageX;A=l?Math.abs(q)<Math.abs(b.touches[0].pageX-g):Math.abs(q)<Math.abs(b.touches[0].pageY-g);if(!A||500<Number(new Date)-x)b.preventDefault(),!r&&a.transitions&&(e.animationLoop||(q/=0===a.currentSlide&&0>q||a.currentSlide===a.last&&0<q?Math.abs(q)/k+2:1),a.setProps(m+q,"setTouch"))}function c(){d.removeEventListener("touchmove",
b,!1);if(a.animatingTo===a.currentSlide&&!A&&null!==q){var f=p?-q:q,l=0<f?a.getTarget("next"):a.getTarget("prev");a.canAdvance(l)&&(550>Number(new Date)-x&&50<Math.abs(f)||Math.abs(f)>k/2)?a.flexAnimate(l,e.pauseOnAction):r||a.flexAnimate(a.currentSlide,e.pauseOnAction,!0)}d.removeEventListener("touchend",c,!1);m=q=g=h=null}var h,g,m,k,q,x,A=!1;d.addEventListener("touchstart",function(f){a.animating?f.preventDefault():1===f.touches.length&&(a.pause(),k=l?a.h:a.w,x=Number(new Date),m=n&&p&&a.animatingTo===
a.last?0:n&&p?a.limit-(a.itemW+e.itemMargin)*a.move*a.animatingTo:n&&a.currentSlide===a.last?a.limit:n?(a.itemW+e.itemMargin)*a.move*a.currentSlide:p?(a.last-a.currentSlide+a.cloneOffset)*k:(a.currentSlide+a.cloneOffset)*k,h=l?f.touches[0].pageY:f.touches[0].pageX,g=l?f.touches[0].pageX:f.touches[0].pageY,d.addEventListener("touchmove",b,!1),d.addEventListener("touchend",c,!1))},!1)},resize:function(){!a.animating&&a.is(":visible")&&(n||a.doMath(),r?k.smoothHeight():n?(a.slides.width(a.computedW),
a.update(a.pagingCount),a.setProps()):l?(a.viewport.height(a.h),a.setProps(a.h,"setTotal")):(e.smoothHeight&&k.smoothHeight(),a.newSlides.width(a.computedW),a.setProps(a.computedW,"setTotal")))},smoothHeight:function(b){if(!l||r){var c=r?a:a.viewport;b?c.animate({height:a.slides.eq(a.animatingTo).height()},b):c.height(a.slides.eq(a.animatingTo).height())}},sync:function(b){var d=c(e.sync).data("flexslider"),f=a.animatingTo;switch(b){case "animate":d.flexAnimate(f,e.pauseOnAction,!1,!0);break;case "play":d.playing||
d.asNav||d.play();break;case "pause":d.pause()}}};a.flexAnimate=function(b,d,m,v,w){q&&1===a.pagingCount&&(a.direction=a.currentItem<b?"next":"prev");if(!a.animating&&(a.canAdvance(b,w)||m)&&a.is(":visible")){if(q&&v)if(m=c(e.asNavFor).data("flexslider"),a.atEnd=0===b||b===a.count-1,m.flexAnimate(b,!0,!1,!0,w),a.direction=a.currentItem<b?"next":"prev",m.direction=a.direction,Math.ceil((b+1)/a.visible)-1!==a.currentSlide&&0!==b)a.currentItem=b,a.slides.removeClass(g+"active-slide").eq(b).addClass(g+
"active-slide"),b=Math.floor(b/a.visible);else return a.currentItem=b,a.slides.removeClass(g+"active-slide").eq(b).addClass(g+"active-slide"),!1;a.animating=!0;a.animatingTo=b;e.before(a);d&&a.pause();a.syncExists&&!w&&k.sync("animate");e.controlNav&&k.controlNav.active();n||a.slides.removeClass(g+"active-slide").eq(b).addClass(g+"active-slide");a.atEnd=0===b||b===a.last;e.directionNav&&k.directionNav.update();b===a.last&&(e.end(a),e.animationLoop||a.pause());if(r)h?(a.slides.eq(a.currentSlide).css({opacity:0,
zIndex:1}),a.slides.eq(b).css({opacity:1,zIndex:2}),a.slides.unbind("webkitTransitionEnd transitionend"),a.slides.eq(a.currentSlide).bind("webkitTransitionEnd transitionend",function(){e.after(a)}),a.animating=!1,a.currentSlide=a.animatingTo):(a.slides.eq(a.currentSlide).fadeOut(e.animationSpeed,e.easing),a.slides.eq(b).fadeIn(e.animationSpeed,e.easing,a.wrapup));else{var f=l?a.slides.filter(":first").height():a.computedW;n?(b=e.itemWidth>a.w?2*e.itemMargin:e.itemMargin,b=(a.itemW+b)*a.move*a.animatingTo,
b=b>a.limit&&1!==a.visible?a.limit:b):b=0===a.currentSlide&&b===a.count-1&&e.animationLoop&&"next"!==a.direction?p?(a.count+a.cloneOffset)*f:0:a.currentSlide===a.last&&0===b&&e.animationLoop&&"prev"!==a.direction?p?0:(a.count+1)*f:p?(a.count-1-b+a.cloneOffset)*f:(b+a.cloneOffset)*f;a.setProps(b,"",e.animationSpeed);a.transitions?(e.animationLoop&&a.atEnd||(a.animating=!1,a.currentSlide=a.animatingTo),a.container.unbind("webkitTransitionEnd transitionend"),a.container.bind("webkitTransitionEnd transitionend",
function(){a.wrapup(f)})):a.container.animate(a.args,e.animationSpeed,e.easing,function(){a.wrapup(f)})}e.smoothHeight&&k.smoothHeight(e.animationSpeed)}};a.wrapup=function(b){!r&&!n&&(0===a.currentSlide&&a.animatingTo===a.last&&e.animationLoop?a.setProps(b,"jumpEnd"):a.currentSlide===a.last&&0===a.animatingTo&&e.animationLoop&&a.setProps(b,"jumpStart"));a.animating=!1;a.currentSlide=a.animatingTo;e.after(a)};a.animateSlides=function(){a.animating||a.flexAnimate(a.getTarget("next"))};a.pause=function(){clearInterval(a.animatedSlides);
a.playing=!1;e.pausePlay&&k.pausePlay.update("play");a.syncExists&&k.sync("pause")};a.play=function(){a.animatedSlides=setInterval(a.animateSlides,e.slideshowSpeed);a.playing=!0;e.pausePlay&&k.pausePlay.update("pause");a.syncExists&&k.sync("play")};a.canAdvance=function(b,c){var d=q?a.pagingCount-1:a.last;return c?!0:q&&a.currentItem===a.count-1&&0===b&&"prev"===a.direction?!0:q&&0===a.currentItem&&b===a.pagingCount-1&&"next"!==a.direction?!1:b!==a.currentSlide||q?e.animationLoop?!0:a.atEnd&&0===
a.currentSlide&&b===d&&"next"!==a.direction?!1:a.atEnd&&a.currentSlide===d&&0===b&&"next"===a.direction?!1:!0:!1};a.getTarget=function(b){a.direction=b;return"next"===b?a.currentSlide===a.last?0:a.currentSlide+1:0===a.currentSlide?a.last:a.currentSlide-1};a.setProps=function(b,c,d){var f=b?b:(a.itemW+e.itemMargin)*a.move*a.animatingTo;var h=-1*function(){if(n)return"setTouch"===c?b:p&&a.animatingTo===a.last?0:p?a.limit-(a.itemW+e.itemMargin)*a.move*a.animatingTo:a.animatingTo===a.last?a.limit:f;switch(c){case "setTotal":return p?
(a.count-1-a.currentSlide+a.cloneOffset)*b:(a.currentSlide+a.cloneOffset)*b;case "setTouch":return b;case "jumpEnd":return p?b:a.count*b;case "jumpStart":return p?a.count*b:b;default:return b}}()+"px";a.transitions&&(h=l?"translate3d(0,"+h+",0)":"translate3d("+h+",0,0)",d=void 0!==d?d/1E3+"s":"0s",a.container.css("-"+a.pfx+"-transition-duration",d));a.args[a.prop]=h;(a.transitions||void 0===d)&&a.container.css(a.args)};a.setup=function(b){if(r)a.slides.css({width:"100%","float":"left",marginRight:"-100%",
position:"relative"}),"init"===b&&(h?a.slides.css({opacity:0,display:"block",webkitTransition:"opacity "+e.animationSpeed/1E3+"s ease",zIndex:1}).eq(a.currentSlide).css({opacity:1,zIndex:2}):a.slides.eq(a.currentSlide).fadeIn(e.animationSpeed,e.easing)),e.smoothHeight&&k.smoothHeight();else{var d;"init"===b&&(a.viewport=c('<div class="'+g+'viewport"></div>').css({overflow:"hidden",position:"relative"}).appendTo(a).append(a.container),a.cloneCount=0,a.cloneOffset=0,p&&(d=c.makeArray(a.slides).reverse(),
a.slides=c(d),a.container.empty().append(a.slides)));e.animationLoop&&!n&&(a.cloneCount=2,a.cloneOffset=1,"init"!==b&&a.container.find(".clone").remove(),a.container.append(a.slides.first().clone().addClass("clone")).prepend(a.slides.last().clone().addClass("clone")));a.newSlides=c(e.selector,a);var f=p?a.count-1-a.currentSlide+a.cloneOffset:a.currentSlide+a.cloneOffset;l&&!n?(a.container.height(200*(a.count+a.cloneCount)+"%").css("position","absolute").width("100%"),setTimeout(function(){a.newSlides.css({display:"block"});
a.doMath();a.viewport.height(a.h);a.setProps(f*a.h,"init")},"init"===b?100:0)):(a.container.width(200*(a.count+a.cloneCount)+"%"),a.setProps(f*a.computedW,"init"),setTimeout(function(){a.doMath();a.newSlides.css({width:a.computedW,"float":"left",display:"block"});e.smoothHeight&&k.smoothHeight()},"init"===b?100:0))}n||a.slides.removeClass(g+"active-slide").eq(a.currentSlide).addClass(g+"active-slide")};a.doMath=function(){var b=a.slides.first(),c=e.itemMargin,d=e.minItems,h=e.maxItems;a.w=a.width();
a.h=b.height();a.boxPadding=b.outerWidth()-b.width();n?(a.itemT=e.itemWidth+c,a.minW=d?d*a.itemT:a.w,a.maxW=h?h*a.itemT:a.w,a.itemW=a.minW>a.w?(a.w-c*d)/d:a.maxW<a.w?(a.w-c*h)/h:e.itemWidth>a.w?a.w:e.itemWidth,a.visible=Math.floor(a.w/(a.itemW+c)),a.move=0<e.move&&e.move<a.visible?e.move:a.visible,a.pagingCount=Math.ceil((a.count-a.visible)/a.move+1),a.last=a.pagingCount-1,a.limit=1===a.pagingCount?0:e.itemWidth>a.w?(a.itemW+2*c)*a.count-a.w-c:(a.itemW+c)*a.count-a.w-c):(a.itemW=a.w,a.pagingCount=
a.count,a.last=a.count-1);a.computedW=a.itemW-a.boxPadding};a.update=function(b,c){a.doMath();n||(b<a.currentSlide?a.currentSlide+=1:b<=a.currentSlide&&0!==b&&--a.currentSlide,a.animatingTo=a.currentSlide);if(e.controlNav&&!a.manualControls)if("add"===c&&!n||a.pagingCount>a.controlNav.length)k.controlNav.update("add");else if("remove"===c&&!n||a.pagingCount<a.controlNav.length)n&&a.currentSlide>a.last&&(--a.currentSlide,--a.animatingTo),k.controlNav.update("remove",a.last);e.directionNav&&k.directionNav.update()};
a.addSlide=function(b,d){var f=c(b);a.count+=1;a.last=a.count-1;l&&p?void 0!==d?a.slides.eq(a.count-d).after(f):a.container.prepend(f):void 0!==d?a.slides.eq(d).before(f):a.container.append(f);a.update(d,"add");a.slides=c(e.selector+":not(.clone)",a);a.setup();e.added(a)};a.removeSlide=function(b){var d=isNaN(b)?a.slides.index(c(b)):b;--a.count;a.last=a.count-1;isNaN(b)?c(b,a.slides).remove():l&&p?a.slides.eq(a.last).remove():a.slides.eq(b).remove();a.doMath();a.update(d,"remove");a.slides=c(e.selector+
":not(.clone)",a);a.setup();e.removed(a)};k.init()};c.flexslider.defaults={namespace:"flex-",selector:".slides > li",animation:"fade",easing:"swing",direction:"horizontal",reverse:!1,animationLoop:!0,smoothHeight:!1,startAt:0,slideshow:!0,slideshowSpeed:7E3,animationSpeed:600,initDelay:0,randomize:!1,pauseOnAction:!0,pauseOnHover:!1,useCSS:!0,touch:!0,video:!1,controlNav:!0,directionNav:!0,prevText:"<i></i>",nextText:"<i></i>",keyboard:!0,multipleKeyboard:!1,mousewheel:!1,pausePlay:!1,pauseText:"Pause",
playText:"Play",controlsContainer:"",manualControls:"",sync:"",asNavFor:"",itemWidth:0,itemMargin:0,minItems:0,maxItems:0,move:0,start:function(){},before:function(){},after:function(){},end:function(){},added:function(){},removed:function(){}};c.fn.flexslider=function(d){void 0===d&&(d={});if("object"===typeof d)return this.each(function(){var a=c(this),b=a.find(d.selector?d.selector:".slides > li");1===b.length?(b.fadeIn(400),d.start&&d.start(a)):void 0==a.data("flexslider")&&new c.flexslider(this,
d)});var b=c(this).data("flexslider");switch(d){case "play":b.play();break;case "pause":b.pause();break;case "next":b.flexAnimate(b.getTarget("next"),!0);break;case "prev":case "previous":b.flexAnimate(b.getTarget("prev"),!0);break;default:"number"===typeof d&&b.flexAnimate(d,!0)}}})(jQuery);
var shuffleArray=function(c){var d=c.length;if(0===d)return!1;for(;--d;){var b=Math.floor(Math.random()*(d+1));var a=c[d];c[d]=c[b];c[b]=a}return c},getRandomInt=function(c,d){return Math.floor(Math.random()*(d-c+1))+c};
(function(c){c.organicTabs=function(d,b){var a=this;a.$el=c(d);a.$nav=a.$el.find(".navtab");a.init=function(){a.options=c.extend({},c.organicTabs.defaultOptions,b);c(".hide").css({position:"relative",top:0,left:0,display:"none"});a.$nav.delegate("li > a","click",function(){var b=a.$el.find("a.current").attr("href").substring(1),d=c(this),h=d.attr("href").substring(1),m=a.$el.find(".list-tabwrap"),l=m.height();m.height(l);h!=b&&0==a.$el.find(":animated").length&&a.$el.find("#"+b).fadeOut(a.options.speed,
function(){a.$el.find("#"+h).fadeIn(a.options.speed);var b=a.$el.find("#"+h).height();m.animate({height:b});a.$el.find(".navtab li a").removeClass("current");d.addClass("current")});return!1})};a.init()};c.organicTabs.defaultOptions={speed:300};c.fn.organicTabs=function(d){return this.each(function(){new c.organicTabs(this,d)})}})(jQuery);
(function(c){function d(a,b){this.el=c(a);this.options=b||{};this.x=!1!==this.options.x||this.options.forceHorizontal;this.y=!1!==this.options.y||this.options.forceVertical;this.autoHide=!1!==this.options.autoHide;this.padding=void 0==this.options.padding?2:this.options.padding;this.inner=this.el.find(".antiscroll-inner");this.inner.css({width:"+="+(this.y?e():0),height:"+="+(this.x?e():0)});this.refresh()}function b(a){this.pane=a;this.pane.el.append(this.el);this.innerEl=this.pane.inner.get(0);
this.shown=this.enter=this.dragging=!1;this.pane.el.mouseenter(c.proxy(this,"mouseenter"));this.pane.el.mouseleave(c.proxy(this,"mouseleave"));this.el.mousedown(c.proxy(this,"mousedown"));this.innerPaneScrollListener=c.proxy(this,"scroll");this.pane.inner.scroll(this.innerPaneScrollListener);this.innerPaneMouseWheelListener=c.proxy(this,"mousewheel");this.pane.inner.bind("mousewheel",this.innerPaneMouseWheelListener);a=this.pane.options.initialDisplay;!1!==a&&(this.show(),this.pane.autoHide&&(this.hiding=
setTimeout(c.proxy(this,"hide"),parseInt(a,10)||3E3)))}function a(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c}function e(){if(void 0===g){var a=c('<div class="antiscroll-inner" style="width:50px;height:50px;overflow-y:scroll;position:absolute;top:-200px;left:-200px;"><div style="height:100px;width:100%"></div>');c("body").append(a);var b=c(a).innerWidth(),d=c("div",a).innerWidth();c(a).remove();g=b-d}return g}c.fn.antiscroll=function(a){return this.each(function(){c(this).data("antiscroll")&&
c(this).data("antiscroll").destroy();c(this).data("antiscroll",new c.Antiscroll(this,a))})};c.Antiscroll=d;d.prototype.refresh=function(){var a=this.inner.get(0).scrollWidth>this.el.width()+(this.y?e():0),c=this.inner.get(0).scrollHeight>this.el.height()+(this.x?e():0);this.x&&(!this.horizontal&&a?this.horizontal=new b.Horizontal(this):this.horizontal&&!a?(this.horizontal.destroy(),this.horizontal=null):this.horizontal&&this.horizontal.update());this.y&&(!this.vertical&&c?this.vertical=new b.Vertical(this):
this.vertical&&!c?(this.vertical.destroy(),this.vertical=null):this.vertical&&this.vertical.update())};d.prototype.destroy=function(){this.horizontal&&(this.horizontal.destroy(),this.horizontal=null);this.vertical&&(this.vertical.destroy(),this.vertical=null);return this};d.prototype.rebuild=function(){this.destroy();this.inner.attr("style","");d.call(this,this.el,this.options);return this};b.prototype.destroy=function(){this.el.remove();this.pane.inner.unbind("scroll",this.innerPaneScrollListener);
this.pane.inner.unbind("mousewheel",this.innerPaneMouseWheelListener);return this};b.prototype.mouseenter=function(){this.enter=!0;this.show()};b.prototype.mouseleave=function(){this.enter=!1;this.dragging||this.pane.autoHide&&this.hide()};b.prototype.scroll=function(){this.shown||(this.show(),this.enter||this.dragging||!this.pane.autoHide||(this.hiding=setTimeout(c.proxy(this,"hide"),1500)));this.update()};b.prototype.mousedown=function(a){a.preventDefault();this.dragging=!0;this.startPageY=a.pageY-
parseInt(this.el.css("top"),10);this.startPageX=a.pageX-parseInt(this.el.css("left"),10);this.el[0].ownerDocument.onselectstart=function(){return!1};var b=c.proxy(this,"mousemove"),d=this;c(this.el[0].ownerDocument).mousemove(b).mouseup(function(){d.dragging=!1;this.onselectstart=null;c(this).unbind("mousemove",b);d.enter||d.hide()})};b.prototype.show=function(a){!this.shown&&this.update()&&(this.el.addClass("antiscroll-scrollbar-shown"),this.hiding&&(clearTimeout(this.hiding),this.hiding=null),this.shown=
!0)};b.prototype.hide=function(){!1!==this.pane.autoHide&&this.shown&&(this.el.removeClass("antiscroll-scrollbar-shown"),this.shown=!1)};b.Horizontal=function(a){this.el=c('<div class="antiscroll-scrollbar antiscroll-scrollbar-horizontal">',a.el);b.call(this,a)};a(b.Horizontal,b);b.Horizontal.prototype.update=function(){var a=this.pane.el.width(),b=a-2*this.pane.padding,c=this.pane.inner.get(0);this.el.css("width",b*a/c.scrollWidth).css("left",b*c.scrollLeft/c.scrollWidth);return a<c.scrollWidth};
b.Horizontal.prototype.mousemove=function(a){var b=this.pane.el.width()-2*this.pane.padding,c=a.pageX-this.startPageX;a=this.el.width();var d=this.pane.inner.get(0);c=Math.min(Math.max(c,0),b-a);d.scrollLeft=(d.scrollWidth-this.pane.el.width())*c/(b-a)};b.Horizontal.prototype.mousewheel=function(a,b,c,d){if(0>c&&0==this.pane.inner.get(0).scrollLeft||0<c&&this.innerEl.scrollLeft+Math.ceil(this.pane.el.width())==this.innerEl.scrollWidth)return a.preventDefault(),!1};b.Vertical=function(a){this.el=c('<div class="antiscroll-scrollbar antiscroll-scrollbar-vertical">',
a.el);b.call(this,a)};a(b.Vertical,b);b.Vertical.prototype.update=function(){var a=this.pane.el.height(),b=a-2*this.pane.padding,c=this.innerEl,d=b*a/c.scrollHeight;d=20>d?20:d;var e=b*c.scrollTop/c.scrollHeight;e+d>b&&(e=e-(e+d-b)-3);this.el.css("height",d).css("top",e);return a<c.scrollHeight};b.Vertical.prototype.mousemove=function(a){var b=this.pane.el.height(),c=b-2*this.pane.padding;a=a.pageY-this.startPageY;var d=this.el.height(),e=this.innerEl;e.scrollTop=(e.scrollHeight-b)*Math.min(Math.max(a,
0),c-d)/(c-d)};b.Vertical.prototype.mousewheel=function(a,b,c,d){if(0<d&&0==this.innerEl.scrollTop||0>d&&this.innerEl.scrollTop+Math.ceil(this.pane.el.height())==this.innerEl.scrollHeight)return a.preventDefault(),!1};var g})(jQuery);
(function(c){c.fn.ticker=function(d){var b=c.extend({},c.fn.ticker.defaults,d);if(0==c(this).length)return window.console&&window.console.log?window.console.log("Element does not exist in DOM!"):alert("Element does not exist in DOM!"),!1;var a="#"+c(this).attr("id"),e=c(this).get(0).tagName;return this.each(function(){function d(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}function h(a){b.debugMode&&(window.console&&window.console.log?window.console.log(a):alert(a))}function m(){if(0==
f.contentLoaded)if(b.ajaxFeed)"xml"==b.feedType?c.ajax({url:b.feedUrl,cache:!1,dataType:b.feedType,async:!0,success:function(a){for(var c=count=0;c<a.childNodes.length;c++)"rss"==a.childNodes[c].nodeName&&(xmlContent=a.childNodes[c]);for(a=0;a<xmlContent.childNodes.length;a++)"channel"==xmlContent.childNodes[a].nodeName&&(xmlChannel=xmlContent.childNodes[a]);for(a=0;a<xmlChannel.childNodes.length;a++)if("item"==xmlChannel.childNodes[a].nodeName){xmlItems=xmlChannel.childNodes[a];c=!1;for(var e=0;e<
xmlItems.childNodes.length;e++){if("title"==xmlItems.childNodes[e].nodeName)var g=xmlItems.childNodes[e].lastChild.nodeValue;else"link"==xmlItems.childNodes[e].nodeName&&(c=xmlItems.childNodes[e].lastChild.nodeValue);!1!==g&&""!=g&&!1!==c&&(f.newsArr["item-"+count]={type:b.titleText,content:'<a href="'+c+'">'+g+"</a>"},count++,c=g=!1)}}if(d(1>f.newsArr))return h("Couldn't find any content from the XML feed for the ticker to use!"),!1;f.contentLoaded=!0;l()}}):h("Code Me!");else if(b.htmlFeed)if(0<
c(a+" LI").length)c(a+" LI").each(function(a){f.newsArr["item-"+a]={type:b.titleText,content:c(this).html()}});else return h("Couldn't find HTML any content for the ticker to use!"),!1;else return h("The ticker is set to not use any types of content! Check the settings for the ticker."),!1}function l(){f.contentLoaded=!0;c(f.dom.titleElem).html(f.newsArr["item-"+f.position].type);c(f.dom.contentID).html(f.newsArr["item-"+f.position].content);f.position==d(f.newsArr)-1?f.position=0:f.position++;distance=
c(f.dom.contentID).width();time=distance/b.speed;p()}function p(){c(f.dom.contentID).css("opacity","1");if(f.play){var a=c(f.dom.titleID).width()+20;c(f.dom.revealID).css(b.direction,a+"px");"fade"==b.displayType?c(f.dom.revealID).hide(0,function(){c(f.dom.contentID).css(b.direction,a+"px").fadeIn(b.fadeInSpeed,n)}):"scroll"!=b.displayType&&c(f.dom.revealElem).show(0,function(){c(f.dom.contentID).css(b.direction,a+"px").show();animationAction={marginRight:distance+"px"};c(f.dom.revealID).css("margin-"+
b.direction,"0px").delay(20).animate(animationAction,time,"linear",n)})}else return!1}function n(){f.play?(c(f.dom.contentID).delay(b.pauseOnItems).fadeOut(b.fadeOutSpeed),"fade"==b.displayType?c(f.dom.contentID).fadeOut(b.fadeOutSpeed,function(){c(f.dom.wrapperID).find(f.dom.revealElem+","+f.dom.contentID).hide().end().find(f.dom.tickerID+","+f.dom.revealID).show().end().find(f.dom.tickerID+","+f.dom.revealID).removeAttr("style");l()}):c(f.dom.revealID).hide(0,function(){c(f.dom.contentID).fadeOut(b.fadeOutSpeed,
function(){c(f.dom.wrapperID).find(f.dom.revealElem+","+f.dom.contentID).hide().end().find(f.dom.tickerID+","+f.dom.revealID).show().end().find(f.dom.tickerID+","+f.dom.revealID).removeAttr("style");l()})})):c(f.dom.revealElem).hide()}function r(){f.play=!1;c(f.dom.tickerID+","+f.dom.revealID+","+f.dom.titleID+","+f.dom.titleElem+","+f.dom.revealElem+","+f.dom.contentID).stop(!0,!0);c(f.dom.revealID+","+f.dom.revealElem).hide();c(f.dom.wrapperID).find(f.dom.titleID+","+f.dom.titleElem).show().end().find(f.dom.contentID).show()}
function q(a){r();switch(a){case "prev":f.position=0==f.position?d(f.newsArr)-2:1==f.position?d(f.newsArr)-1:f.position-2;c(f.dom.titleElem).html(f.newsArr["item-"+f.position].type);c(f.dom.contentID).html(f.newsArr["item-"+f.position].content);break;case "next":c(f.dom.titleElem).html(f.newsArr["item-"+f.position].type),c(f.dom.contentID).html(f.newsArr["item-"+f.position].content)}f.position==d(f.newsArr)-1?f.position=0:f.position++}var k=(new Date).getTime(),f={position:0,time:0,distance:0,newsArr:{},
play:!0,paused:!1,contentLoaded:!1,dom:{contentID:"#ticker-content-"+k,titleID:"#ticker-title-"+k,titleElem:"#ticker-title-"+k+" SPAN",tickerID:"#ticker-"+k,wrapperID:"#ticker-wrapper-"+k,revealID:"#ticker-swipe-"+k,revealElem:"#ticker-swipe-"+k+" SPAN",controlsID:"#ticker-controls-"+k,prevID:"#prev-"+k,nextID:"#next-"+k,playPauseID:"#play-pause-"+k}};if("UL"!=e&&"OL"!=e&&!0===b.htmlFeed)return h("Cannot use <"+e.toLowerCase()+"> type of element for this plugin - must of type <ul> or <ol>"),!1;b.direction=
"right";(function(){m();c(a).wrap('<div id="'+f.dom.wrapperID.replace("#","")+'"></div>');c(f.dom.wrapperID).children().remove();c(f.dom.wrapperID).append('<div id="'+f.dom.tickerID.replace("#","")+'" class="ticker"><div id="'+f.dom.titleID.replace("#","")+'" class="ticker-title"><span>\x3c!-- --\x3e</span></div><p id="'+f.dom.contentID.replace("#","")+'" class="ticker-content"></p><div id="'+f.dom.revealID.replace("#","")+'" class="ticker-swipe"><span>\x3c!-- --\x3e</span></div></div>');c(f.dom.wrapperID).removeClass("no-js").addClass("ticker-wrapper has-js "+
b.direction);c(f.dom.tickerElem+","+f.dom.contentID).hide();b.controls&&(c(f.dom.controlsID).live("click mouseover mousedown mouseout mouseup",function(a){var b=a.target.id;if("click"==a.type)switch(b){case f.dom.prevID.replace("#",""):f.paused=!0;c(f.dom.playPauseID).addClass("paused");q("prev");break;case f.dom.nextID.replace("#",""):f.paused=!0;c(f.dom.playPauseID).addClass("paused");q("next");break;case f.dom.playPauseID.replace("#",""):1==f.play?(f.paused=!0,c(f.dom.playPauseID).addClass("paused"),
r()):(f.paused=!1,c(f.dom.playPauseID).removeClass("paused"),f.play=!0,f.paused=!1,n())}else"mouseover"==a.type&&c("#"+b).hasClass("controls")?c("#"+b).addClass("over"):"mousedown"==a.type&&c("#"+b).hasClass("controls")?c("#"+b).addClass("down"):"mouseup"==a.type&&c("#"+b).hasClass("controls")?c("#"+b).removeClass("down"):"mouseout"==a.type&&c("#"+b).hasClass("controls")&&c("#"+b).removeClass("over")}),c(f.dom.wrapperID).append('<ul id="'+f.dom.controlsID.replace("#","")+'" class="ticker-controls"><li id="'+
f.dom.prevID.replace("#","")+'" class="jnt-prev controls"><a href="">\x3c!-- --\x3e</a></li><li id="'+f.dom.playPauseID.replace("#","")+'" class="jnt-play-pause controls"><a href="">\x3c!-- --\x3e</a></li><li id="'+f.dom.nextID.replace("#","")+'" class="jnt-next controls"><a href="">\x3c!-- --\x3e</a></li></ul>'));"fade"!=b.displayType&&c(f.dom.contentID).mouseover(function(){0==f.paused&&r()}).mouseout(function(){0==f.paused&&(f.play=!0,f.paused=!1,n())});b.ajaxFeed||l()})()})};c.fn.ticker.defaults=
{speed:.1,ajaxFeed:!1,feedUrl:"",feedType:"xml",displayType:"reveal",htmlFeed:!0,debugMode:!0,controls:!0,titleText:"Latest",direction:"rtl",pauseOnItems:3E3,fadeInSpeed:600,fadeOutSpeed:300}})(jQuery);
function details(c){c("a.moreinfo").toggle(function(){var d=c(this),b=d.parents(".post");d.addClass("active");b.find(".datex").animate({top:"-80px"},{duration:500,queue:!1});b.find(".post-footer").fadeIn();return!1},function(){var d=c(this),b=d.parents(".post");d.removeClass("active");b.find(".post-footer").fadeOut();b.find(".datex").animate({top:0},{duration:500,queue:!0});return!1})}
function datenya(c){c(".timestamp-link abbr.published").each(function(){var d=c(this).attr("title"),b="\u064a\u0646\u0627\u064a\u0631 \u0641\u0628\u0631\u0627\u064a\u0631 \u0645\u0627\u0631\u0633 \u0623\u0628\u0631\u064a\u0644 \u0645\u0627\u064a\u0648 \u064a\u0648\u0646\u064a\u0648 \u064a\u0648\u0644\u064a\u0648 \u0623\u063a\u0633\u0637\u0633 \u0633\u0628\u062a\u0645\u0628\u0631 \u0623\u0643\u062a\u0648\u0628\u0631 \u0646\u0648\u0641\u0645\u0628\u0631 \u062f\u064a\u0633\u0645\u0628\u0631".split(" ");if(""!=
d){var a=d.substring(0,10),e=a.substring(0,4),g=a.substring(5,7);a=a.substring(8,10);g=b[parseInt(g,10)-1]}b=c(this).parents(".post").children(".datex");b.removeClass("hidex").addClass("show");c("strong",b).html(a);c("small",b).html(e);c("span",b).html(g)})}
(function(c){function d(){h||(h=!0,a?(e.find("a").hide(),e.find("img").show(),c.ajax(a,{dataType:"html"}).done(function(b){b=c("<div></div>").append(b.replace(p,""));var d=b.find("a.blog-pager-older-link");d?a=d.attr("href"):(a="",e.hide());b=b.find(g).children();c(g).append(b);c(document).ready(function(){c(".post-home img").attr("src",function(a,b){return b.replace("s72-c","s640")});c(".post-home img").attr("src",function(a,b){return b.replace("/default.jpg","/mqdefault.jpg")})});(function(a){a.fn.resizeToParent=
function(b){function c(a){a.css({width:"",height:"","margin-left":"","margin-top":""});var c=a.parents(b.parent).width(),d=a.parents(b.parent).height(),e=a.width(),f=a.height(),g=e/c;f/g<d?(a.css({width:"auto",height:d}),e/=f/d,f=d):(a.css({height:"auto",width:c}),e=c,f/=g);a.css({"margin-left":(e-c)/-2,"margin-top":(f-d)/-2})}b=a.extend({parent:"div",delay:100},b);var d,e=this;a(window).on("resize",function(){clearTimeout(d);d=setTimeout(function(){e.each(function(){c(a(this))})},b.delay)});return this.each(function(){var b=
a(this);b.attr("src",b.attr("src"));b.load(function(){c(b)});this.complete&&c(b)})}})(jQuery);c(document).ready(function(){c(".post-thumbnail img").resizeToParent()});c(document).ready(function(){c(".thumb-load").remove()});window._gaq&&window._gaq.push(["_trackPageview",a]);window.gapi&&window.gapi.plusone&&window.gapi.plusone.go&&window.gapi.plusone.go();window.disqus_shortname&&c.getScript("https://"+window.disqus_shortname+".disqus.com/blogger_index.js");window.FB&&window.FB.XFBML&&window.FB.XFBML.parse&&
window.FB.XFBML.parse();window.twttr&&window.twttr.widgets&&window.twttr.widgets.load&&window.twttr.widgets.load();e.find("img").hide();e.find("a").show();h=!1})):e.hide())}function b(){var a=Math.max(m.height(),l.height(),document.documentElement.clientHeight),b=m.scrollTop()+m.height();0>a-b&&d()}var a="",e=null,g="div.blog-posts",h=!1,m=c(window),l=c(document),p=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi;c(document).ready(function(){if("item"!=_WidgetManager._GetAllData().blog.pageType&&
(a=c("a.blog-pager-older-link").attr("href"))){var g=c('<a href="javascript:;"><i class="fa fa-spin fa-circle-o-notch"></i> \u0623\u0638\u0647\u0631 \u0627\u0644\u0645\u0632\u064a\u062f \u0645\u0646 \u0627\u0644\u0645\u0648\u0636\u0648\u0639\u0627\u062a </a>');g.click(d);var h=c('<img src="https://lh3.googleusercontent.com/U6vbIClDtlgu-VrM40cSIWh4Shq7MNs5yCGfZno05uTcgrJ6ivnPJvr8YFTEJY3lp4zDTQVM4cI2ozH1Nppb6XkJLRoukdXfAwLuTYhCXjK6PbJ5caLeLvV6J-ueQvXsOg5LXBeib4cDJqXEP45_A0wMQz7S56amKVQ2mFUSu9-6Bp6Ox4hATJs2nw5du8cZZjHtNRDitZK7qkI8IyY1VTQzAmpAFtgW6ceQJ7-OVmeh506SwNj77SdjdO-sY6HeAqggFJQ7urdJ9UGSfjoyXgVWg5aTlLomg_o3knzRnFpL7dcGW5HBKMrIhVJjFSOT5fqaSYjNj4mP9tZvu7QPWgOrnIYlV4RazEMntIM8agCZQ4O5K26NshmLvqP_Ho4x-TjAHQfBlkK9JCuY0ajJrCkp3CIFMX3O3jplk4f3vzBIu5kFnM_hAjmyZzWe3YMT6IOnvZdZr9Iu39TWncqk6Azi5TCwfFzcn08GT5S1yXl4uOfirCTxzywEvwqHy_7acWRPsbMyIXI5yVaJe_J74-8alVUpDfjvJSff3PWz7_QTE0OGBySyBm2HspN5Houydk91yYJY8RuYoZqUrB7gpWUKIesfw78=w160-h24-no?.gif" style="display: none;">');
m.scroll(b);e=c('<div class="loadmore"></div>');e.append(g);e.append(h);e.insertBefore(c("#blog-pager"));c("#blog-pager").hide()}})})(jQuery);
function PageNavi(c){(function(d){var b={pageCount:6,displayPageNum:3,upPageWord:"&#171;",downPageWord:"&#187;"};b=d.extend({},b,c);var a=location.href,e=function(c){for(var d=[],e=1,g=1,h=0,m=0,k=0,f="",t="",u="",v=0,w;w=c.feed.entry[v];v++){var y=w.published.$t.substring(0,19)+w.published.$t.substring(23,29);timestamp=encodeURIComponent(y);w=w.title.$t;""==w||0!=h&&h%b.pageCount!=b.pageCount-1||(-1!=a.indexOf(timestamp)&&(e=g),""!=w&&g++,d[d.length]="/search?updated-max="+timestamp+"&max-results="+
b.pageCount);h++}for(c=0;c<d.length;c++)c>=e-b.displayPageNum-1&&c<e+b.displayPageNum&&(0==m&&c==e-2&&(t=2==e?'<span class="showpage"><a href="/">'+b.upPageWord+"</a></span>":'<span class="showpage"><a href="'+d[c]+'">'+b.upPageWord+"</a></span>",m++),f=c==e-1?f+('<span class="showpagePoint">'+e+"</span>"):0==c?f+'<span class="showpageNum"><a href="/">1</a></span>':f+('<span class="showpageNum"><a href="'+d[c]+'">'+(c+1)+"</a></span>"),0==k&&c==e&&(u='<span class="showpage"> <a href="'+d[c]+'">'+
b.downPageWord+"</a></span>",k++));1<e&&(f=""+t+" "+f+" ");f='<div class="showpageArea">'+f;e<g-1&&(f+=u);1==g&&g++;f+="</div>";d=document.getElementsByName("pageArea");e=document.getElementById("blog-pager");2>=g&&(f="");for(c=0;c<d.length;c++)d[c].innerHTML=f;d&&0<d.length&&(f="");e&&(e.innerHTML=f);jQuery("#blog-pager").css("display","block")},g=function(c){var d=a,e=[],g=-1!=d.indexOf("/search/label/")?d.substr(d.indexOf("/search/label/")+14,d.length):"";g=-1!=g.indexOf("?")?g.substr(0,g.indexOf("?")):
g;var h=1,m=1,k=0,f=0,t=0,u="",v="",w="",y='<span class="showpageNum"><a href="/search/label/'+g+"?&max-results="+b.pageCount+'">';d=a;for(var z=0,x;x=c.feed.entry[z];z++){var A=x.published.$t.substring(0,19)+x.published.$t.substring(23,29);timestamp=encodeURIComponent(A);x=x.title.$t;""==x||0!=k&&k%b.pageCount!=b.pageCount-1||(-1!=d.indexOf(timestamp)&&(h=m),""!=x&&m++,e[e.length]="/search/label/"+g+"?updated-max="+timestamp+"&max-results="+b.pageCount);k++}for(c=0;c<e.length;c++)c>=h-b.displayPageNum-
1&&c<h+b.displayPageNum&&(0==f&&c==h-2&&(v=2==h?y+b.upPageWord+"</a></span>":'<span class="showpage"><a href="'+e[c]+'">'+b.upPageWord+"</a></span>",f++),u=c==h-1?u+('<span class="showpagePoint">'+h+"</span>"):0==c?y+"1</a></span>":u+('<span class="showpageNum"><a href="'+e[c]+'">'+(c+1)+"</a></span>"),0==t&&c==h&&(w='<span class="showpage"> <a href="'+e[c]+'">'+b.downPageWord+"</a></span>",t++));1<h&&(u=""+v+" "+u+" ");u='<div class="showpageArea">'+u;h<m-1&&(u+=w);1==m&&m++;u+="</div>";e=document.getElementsByName("pageArea");
h=document.getElementById("blog-pager");2>=m&&(u="");for(c=0;c<e.length;c++)e[c].innerHTML=u;e&&0<e.length&&(u="");h&&(h.innerHTML=u);jQuery("#blog-pager").css("display","block")};if(-1!=a.indexOf("/search/label/"))var h=-1!=a.indexOf("?updated-max")?a.substring(a.indexOf("/search/label/")+14,a.indexOf("?updated-max")):a.substring(a.indexOf("/search/label/")+14,a.indexOf("?&max"));-1==a.indexOf("?q=")&&(-1==a.indexOf("/search/label/")?d.get("/feeds/posts/summary?max-results=99999&orderby=published&alt=json-in-script",
e,"jsonp"):d.get("/feeds/posts/full/-/"+h+"?max-results=99999&orderby=published&alt=json-in-script",g,"jsonp"))})(jQuery)}
function RecentComments(c){(function(d){var b={blogURL:"",numComments:4,characters:100,id_containrc:"#rcentcomnets",avatarSize:50,loadingClass:"loadingxx",Showimage:!0,defaultAvatar:"https://4.bp.blogspot.com/-AEWksK942OE/UFiyLzXJhiI/AAAAAAAAFKE/jBegaGPClxI/s70/user-anonymous-icon.png",MonthNames:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),maxfeeds:50,adminBlog:""};b=d.extend({},b,c);d(b.id_containrc).addClass(b.loadingClass);d.get((""===b.blogURL?window.location.protocol+"//"+window.location.host:
b.blogURL)+"/feeds/comments/default?alt=json-in-script&orderby=published",function(a){var c=a.feed.entry;if(void 0!==c){a="<ul class='rcomnetxx'>";for(var g=ntotal=0;g<b.maxfeeds;g++){var h;if(g==c.length)break;if(ntotal>=b.numComments)break;var m=c[g];for(h=0;h<m.link.length;h++)if("alternate"==m.link[h].rel)var l=m.link[h].href;for(h=0;h<m.author.length;h++){var p=m.author[h].name.$t;var n=m.author[h].gd$image.src}if(p!=b.adminBlog&&ntotal<b.numComments){ntotal++;a+="<li>";var r="https://img1.blogblog.com/img/blank.gif"==
n?b.defaultAvatar:n.replace(/\/s[0-9]+(\-c|\/)/,"/s"+b.avatarSize+"$1");h=m.author[0].uri?m.author[0].uri.$t:"#nope";a+=!0===b.Showimage?'<a class="kmtimg" href="'+h+'"><img src="'+r+'"  title="'+p+'" alt="'+p+'" style="width:'+b.avatarSize+"px;height:"+b.avatarSize+'px;display:block"/></a>':"";r=l.lastIndexOf("/")+1;var q=l.lastIndexOf(".");r=l.split("-").join(" ").substring(r,q)+"...";var k=m.published.$t.substring(0,10);q=k.substring(0,4);var f=k.substring(5,7);k=k.substring(8,10);f=b.MonthNames[parseInt(f,
10)-1];var t=m.published.$t.substring(11,16);var u=t.substring(0,2),v=t.substring(2,5);t=12>u?"AM":"PM";0===u&&(u=12);12<u&&(u-=12);a+='<div class="ketkomt"><a target="_blank" rel="nofollow" href="'+h+'"><strong>'+p+'</strong></a> on <a class="judulx" href="'+l+'">'+r+'</a><div class="date"><span class="dd">'+k+'</span> <span class="dm">'+f+'</span> <span class="dy">'+q+'</span> <span class="timex">'+u+v+" "+t+"</span></div></div>";m=m.content.$t.replace(/(<([^>]+)>)/gi,"");""!==m&&m.length>b.characters&&
(m=m.substring(0,b.characters),m+="...");a+=0<b.characters?"<p>"+m+"</p>":"";a+="</li>"}}a+="</ul>";d(b.id_containrc).html(a).removeClass(b.loadingClass)}else d(b.id_containrc).html("<span>No result!</span>").removeClass(b.loadingClass)},"jsonp")})(jQuery)}
function menunav(c){c("#mobilenav").click(function(){c("#menunav").slideToggle();c(this).toggleClass("active");return!1});c(".sf-menu ul").each(function(){c(this).parent("li").append("<i></i>")});c(window).on("load resize",function(){var b=c(window).width();767<b?(c("#menunav").css("display","block"),c("#menunav").superfish({animation:{height:"show"},animationOut:{height:"hide"}}),c(".sf-menu i").css("display","none")):767>=b&&"active"===c("#mobilenav").attr("class")?(c("#menunav").css("display",
"block"),c("#menunav").superfish("destroy"),c(".sf-menu i").css("display","block")):767>=b&&"active"!==c("#mobilenav").attr("class")&&(c("#menunav").css("display","none"),c("#menunav").superfish("destroy"),c(".sf-menu i").css("display","block"))});c(".sf-menu i").click(function(){c(this).parent("li").children("ul").slideToggle();c(this).toggleClass("active");return!1});var d=window.location.href;c("#menunav a").each(function(){this.href===d&&c(this).parents("li").children("a").addClass("current")})}
function searchxx(c){(function(d){var b={blogURL:"",srcBlank:"https://1.bp.blogspot.com/-htG7vy9vIAA/Tp0KrMUdoWI/AAAAAAAABAU/e7XkFtErqsU/s1600/grey.gif",findText:"Search results for keyword",NotfindText:"No result!",Showthumb:!0,LoadingText:"Searching...",scrthumbSize:50,summaryLength:100};b=d.extend({},b,c);var a=d("#ajax-search-form"),e=a.find(":text");a.append('<div id="search-result"></div>');var g=d("#search-result");a.on("submit",function(){var a=e.val();g.show().html('<div class="load">'+b.LoadingText+
"</div>");d.get((""===b.blogURL?window.location.protocol+"//"+window.location.host:b.blogURL)+"/feeds/posts/summary?alt=json-in-script&q="+a+"&max-results=9999",function(c){c=c.feed.entry;var d;if(void 0!==c){var e="<h4>"+b.findText+" &quot;"+a+"&quot;</h4>";e+='<a class="close" href="/">&times;</a><ol>';for(var h=0;h<c.length;h++){var m=new RegExp(a,"ig");var q=c[h].title.$t.replace(m,"<mark>"+a+"</mark>");for(var k=0;k<c[h].link.length;k++)if("alternate"==c[h].link[k].rel)var f=c[h].link[k].href;
if(0<b.summaryLength){var t="content"in c[h]?c[h].content.$t:"summary"in c[h]?c[h].summary.$t:"";t=t.replace(/<\S[^>]*>/g,"");t.length>b.summaryLength&&(t=t.substring(0,b.summaryLength)+"...");t=t.replace(m,"<mark>"+a+"</mark>")}!0===b.Showthumb&&(d="media$thumbnail"in c[h]?c[h].media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/s"+b.scrthumbSize+"-c"):b.srcBlank);e+='<li><a href="'+f+'" >'+(!0===b.Showthumb?'<img width="'+b.scrthumbSize+'" height="'+b.scrthumbSize+'" src="'+d+'"/>':"")+"<strong>"+q+"</strong></a>"+
(0<b.summaryLength?"<p>"+t+"</p>":"")+"</li>"}g.html(e+"</ol>")}else g.html('<a class="close" href="/">&times;</a><strong>'+b.NotfindText+"</strong>")},"jsonp");return!1});a.on("click",".close",function(){g.fadeOut();return!1})})(jQuery)}
function NewsTicker(c){(function(d){var b={blogURL:"",MaxPost:4,Speed:.1,direction:"ltr",titleText:"\u0623\u062d\u062f\u062b \u0627\u0644\u0645\u0648\u0636\u0648\u0639\u0627\u062a ",displayType:"reveal",Container:"#newsticker",MonthNames:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")};b=d.extend({},b,c);d(b.Container).addClass("loading");d.get((""===b.blogURL?window.location.protocol+"//"+window.location.host:b.blogURL)+"/feeds/posts/summary?max-results="+b.MaxPost+"&orderby=published&alt=json-in-script",
function(a){var c,g="";a=a.feed.entry;if(void 0!==a){for(var h=0;h<a.length;h++){for(c=0;c<a[h].link.length;c++)if("alternate"==a[h].link[c].rel)var m=a[h].link[c].href;c=a[h].title.$t;var l=a[h].published.$t.substring(0,10);var p=l.substring(0,4);var n=l.substring(5,7);l=l.substring(8,10);n=b.MonthNames[parseInt(n,10)-1];var r=a[h].published.$t.substring(11,16);var q=r.substring(0,2);r=r.substring(2,5);var k=12>q?"AM":"PM";0===q&&(q=12);12<q&&(q-=12);g+='<li class="news-item"><span title="'+n+" "+
l+", "+p+'" class="date">'+q+r+" "+k+'</span> <a class="title" href="'+m+'">'+c+"</a></li>"}d(b.Container).html('<ul class="js-hidden" id="newstick">'+g+"</ul>").removeClass("loading");d("#newstick").ticker({speed:b.Speed,direction:b.direction,titleText:b.titleText,displayType:b.displayType})}else d(b.Container).html("<span>No result!</span>").removeClass("loading")},"jsonp")})(jQuery)}
(function(c){c(window).scroll(function(){280<c(this).scrollTop()?(c("#top").removeAttr("href"),c("#top").fadeIn()):c("#top").fadeOut()});c(function(){c("#top").click(function(){c("html, body").animate({scrollTop:0},"slow");return!1})})})(jQuery);
function relatedPostsWidget(c){(function(d){var b={blogURL:"",maxPosts:5,maxTags:5,maxPostsPerTag:5,containerSelector:"",tags:null,loadingText:"",loadingClass:"loadingxx",relevantTip:"",rlt_summary:0,relatedTitle:"\u0645\u0642\u0627\u0644\u0627\u062a \u0630\u0627\u062a \u0635\u0644\u0629",readMoretext:"[...]",rlpBlank:"https://1.bp.blogspot.com/-htG7vy9vIAA/Tp0KrMUdoWI/AAAAAAAABAU/e7XkFtErqsU/s1600/grey.gif",rlt_thumb:70,recentTitle:"\u0645\u0648\u0636\u0648\u0639\u0627\u062a \u0630\u0627\u062a \u0635\u0644\u0629",
postScoreClass:"",onLoad:!1};b=d.extend({},b,c);var a=0,e=null,g=null;b.containerSelector||(document.write('<div id="related_posts"></div>'),b.containerSelector="#related_posts");var h=function(c,h){a++;if(c.feed.entry)for(var p=0;p<c.feed.entry.length;p++){for(var l=c.feed.entry[p],k="",f=0;f<l.link.length;f++)if("alternate"==l.link[f].rel){k=l.link[f].href;break}f="content"in l?l.content.$t:"summary"in l?l.summary.$t:"";f=f.replace(/<\S[^>]*>/g,"");f.length>b.rlt_summary&&(f=f.substring(0,b.rlt_summary));
var n=l.title.$t,u="media$thumbnail"in l?l.media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/s"+b.rlt_thumb+"-c"):b.rlpBlank;if(location.href.toLowerCase()!=k.toLowerCase())a:{l=k;var v=n,w=f;f=d("li",g);for(k=0;k<f.length;k++){var y=d("a",f.eq(k));n=m(y);if(y.attr("href")==l){l=y;v=++n;l.attr("score",v);b.relevantTip&&l.attr("title",b.relevantTip.replace("d",v));b.postScoreClass&&l.attr("class",b.postScoreClass+v);for(l=k-1;0<=l;l--)if(v=d("a",f.eq(l)),m(v)>n){1<k-l&&f.eq(l).after(f.eq(k));break a}0<
k&&f.eq(0).before(f.eq(k));break a}}g.append('<li><div class="inner"><a class="jdlunya" href="'+l+'" title="'+(b.relevantTip?b.relevantTip.replace("d",1):"")+'"><span class="gmbrrltd"><img style="width:'+b.rlt_thumb+"px;height:"+b.rlt_thumb+'px;display: block" alt="'+v+'" src="'+u+'"/></span><strong>'+v+"</strong></a><p>"+w+'<a title="'+v+'" href="'+l+'">'+b.readMoretext+"</a></p></div></li>")}}a>=b.tags.length&&(g.attr("class",""),d("#related-posts-loadingtext",e).remove(),0<b.maxPosts&&d("li:gt("+
(b.maxPosts-1)+")",g).remove())},m=function(a){a=parseInt(a.attr("score"));return 0<a?a:1},l=function(){if("#related_posts"!=b.containerSelector){var a=d(b.containerSelector);if(1!=a.length)return;e=d('<div id="related_posts"></div>').appendTo(a)}else e=d(b.containerSelector);b.tags||(b.tags=[],d('a[rel="tag"]:lt('+b.maxTags+")").each(function(){var a=d.trim(d(this).text().replace(/\n/g,""));-1==d.inArray(a,b.tags)&&(b.tags[b.tags.length]=a)}));if(0!=b.tags.length||b.recentTitle)if(0==b.tags.length?
d("<h4><span>"+b.recentTitle+"</span></h4>").appendTo(e):b.relatedTitle&&d("<h4><span>"+b.relatedTitle+"</span></h4>").appendTo(e),b.loadingText&&d('<div id="related-posts-loadingtext">'+b.loadingText+"</div>").appendTo(e),g=d("<ul "+(b.loadingClass?'class="'+b.loadingClass+'"':"")+"></ul>").appendTo(e),0==b.tags.length)d.get((""===b.blogURL?window.location.protocol+"//"+window.location.host:b.blogURL)+"/feeds/posts/summary?max-results="+b.maxPostsPerTag+"&orderby=published&alt=json-in-script",h,
"jsonp");else for(a=0;a<b.tags.length;a++)d.get((""===b.blogURL?window.location.protocol+"//"+window.location.host:b.blogURL)+"/feeds/posts/summary/-/"+b.tags[a]+"?max-results="+b.maxPostsPerTag+"&orderby=published&alt=json-in-script",h,"jsonp")};b.onLoad?d(window).load(l):d(document).ready(l)})(jQuery)}
(function(c){c.AutofeaturedPost=function(d,b){var a=this;a.$el=c(d);a.init=function(){a.options=c.extend({},c.AutofeaturedPost.defaultOptions,b);a.$el.html('<div class="featuredpost"><ul class="featpost"></ul></div>').addClass(a.options.loadingClass);var d=function(b){var d,e="";b=!0===a.options.RandompostActive?shuffleArray(b.feed.entry):b.feed.entry;for(var g=0,p=b.length;g<p;g++){var n=b[g].link.length;for(d=0;d<n;d++)if("alternate"==b[g].link[d].rel){var r=b[g].link[d].href;break}for(d=0;d<n;d++)if("replies"==
b[g].link[d].rel&&"text/html"==b[g].link[d].type){var q=b[g].link[d].title.split(" ")[0];break}d="content"in b[g]?b[g].content.$t:"summary"in b[g]?b[g].summary.$t:"";newdowm=c("<div></div>").append(d.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,""));imgb=newdowm.find("img");if("media$thumbnail"in b[g]){var k=b[g].media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/s"+a.options.ImageSize);-1!=b[g].media$thumbnail.url.indexOf("img.youtube.com")&&(k=b[g].media$thumbnail.url.replace("default",
"0"))}else k=0!=imgb.length?imgb[0].src:a.options.pBlank;d=d.replace(/<\S[^>]*>/g,"");d.length>a.options.Summarylength&&(d=d.substring(0,a.options.Summarylength)+"...");n=b[g].title.$t;var f=b[g].published.$t.substring(0,10);var t=f.substring(0,4);var u=f.substring(5,7);f=f.substring(8,10);nmbln=a.options.MonthNames[parseInt(u,10)-1];e+='<li><div class="inner" ><a title="'+n+'" class="feathumb" href="'+r+'"><img src="'+k+'"/></a><strong class="titlex"><a href="'+r+'">'+n+'</a></strong><div class="labeltext"><div class="infolabel">'+
(!0===a.options.ShowDate?'<span class="date"><i class="fa fa-calendar-o"></i>'+nmbln+" "+f+", "+t+"</span>":"")+(!0===a.options.ShowComment?'<span class="comnum"><a href="'+r+'#comment-form">'+("0"===q?a.options.NoCommentText:"1"===q?q+" "+a.options.OneCommentText:q+" "+a.options.CommentText)+"</a></span>":"")+"</span></div><p>"+d+"</p></div></div></li>"}a.$el.find("ul.featpost").append(e);a.$el.find(".featuredpost").flexslider({animation:a.options.animation,selector:".featpost > li",animationLoop:!0,
mousewheel:!0,slideshowSpeed:a.options.slideSpeed,before:function(){a.$el.find(".labeltext").stop().animate({right:-600,opacity:0},1E3);a.$el.find(".titlex").stop().animate({right:700,opacity:0},1E3)},after:function(){a.$el.find(".labeltext").stop().animate({right:10,opacity:.9},1E3);a.$el.find(".titlex").stop().animate({right:10,opacity:.9},1E3)}});a.$el.removeClass(a.options.loadingClass)};!0===a.options.RandompostActive?c.get((""===a.options.blogURL?window.location.protocol+"//"+window.location.host:
a.options.blogURL)+"/feeds/posts/default"+(!1===a.options.tagName?"":"/-/"+a.options.tagName)+"?max-results=0&orderby=published&alt=json-in-script",function(b){b=a.options.MaxPost>b.feed.openSearch$totalResults.$t?1:getRandomInt(1,b.feed.openSearch$totalResults.$t-a.options.MaxPost);c.get((""===a.options.blogURL?window.location.protocol+"//"+window.location.host:a.options.blogURL)+"/feeds/posts/default"+(!1===a.options.tagName?"":"/-/"+a.options.tagName)+"?max-results="+a.options.MaxPost+"&orderby=published&start-index="+
b+"&alt=json-in-script",d,"jsonp")},"jsonp"):c.get((""===a.options.blogURL?window.location.protocol+"//"+window.location.host:a.options.blogURL)+"/feeds/posts/default"+(!1===a.options.tagName?"":"/-/"+a.options.tagName)+"?max-results="+a.options.MaxPost+"&orderby=published&alt=json-in-script",d,"jsonp")};a.init()};c.AutofeaturedPost.defaultOptions={blogURL:"",MaxPost:4,ImageSize:500,Summarylength:150,slideSpeed:5E3,ShowDate:!0,ShowComment:!0,animation:"slide",NoCommentText:"\u0623\u0636\u0641 \u062a\u0639\u0644\u064a\u0642",
OneCommentText:"\u062a\u0639\u0644\u064a\u0642",CommentText:"\u062a\u0639\u0644\u064a\u0642\u0627\u062a",RandompostActive:!0,loadingClass:"loadingxx",MonthNames:"\u064a\u0646\u0627\u064a\u0631 \u0641\u0628\u0631\u0627\u064a\u0631 \u0645\u0627\u0631\u0633 \u0623\u0628\u0631\u064a\u0644 \u0645\u0627\u064a\u0648 \u064a\u0648\u0646\u064a\u0648 \u064a\u0648\u0644\u064a\u0648 \u0623\u063a\u0633\u0637\u0633 \u0633\u0628\u062a\u0645\u0628\u0631 \u0623\u0643\u062a\u0648\u0628\u0631 \u0646\u0648\u0641\u0645\u0628\u0631 \u062f\u064a\u0633\u0645\u0628\u0631".split(" "),
pBlank:"https://1.bp.blogspot.com/-htG7vy9vIAA/Tp0KrMUdoWI/AAAAAAAABAU/e7XkFtErqsU/s72-c/grey.gif",tagName:!1};c.fn.AutofeaturedPost=function(d){return this.each(function(){new c.AutofeaturedPost(this,d)})}})(jQuery);
(function(c){c.RecentPostbyTag=function(d,b){var a=this;a.$el=c(d);a.init=function(){a.options=c.extend({},c.RecentPostbyTag.defaultOptions,b);a.$el.html('<div class="rcbytag '+a.options.postType+'"><ul class="rcentpost"></ul></div>').addClass(a.options.loadingClass);var e=function(b){var e,g="",h=!0===a.options.Random?shuffleArray(b.feed.entry):b.feed.entry;if(void 0!==h){for(var n=a.$el.find(".recntmore"),r=a.$el.find("ul li"),q=h.length,k=0;k<q;k++){var f=h[k].link.length;for(e=0;e<f;e++)if("alternate"==
h[k].link[e].rel){var t=h[k].link[e].href;break}for(e=0;e<f;e++)if("replies"==h[k].link[e].rel&&"text/html"==h[k].link[e].type){var u=h[k].link[e].title.split(" ")[0];break}f="content"in h[k]?h[k].content.$t:"summary"in h[k]?h[k].summary.$t:"";e=c("<div></div>").append(f.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,""));e=e.find("img");if("media$thumbnail"in h[k]){var v=h[k].media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/"+a.options.ImageSize);h[k]===h[0]&&"s"!==a.options.postType?
v=h[k].media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/"+a.options.FirstImageSize):-1!=h[k].media$thumbnail.url.indexOf("img.youtube.com")&&(v=h[k].media$thumbnail.url.replace("default","0"))}else v=0!=e.length?e[0].src:a.options.pBlank;f=f.replace(/<\S[^>]*>/g,"");f.length>a.options.Summarylength&&(f=f.substring(0,a.options.Summarylength)+"...");e=h[k].title.$t;var w=h[k].published.$t.substring(0,10);var y=w.substring(0,4);var z=w.substring(5,7);w=w.substring(8,10);z=a.options.MonthNames[parseInt(z,
10)-1];g+='<li class="a'+k+'"><div class="inner" ><a title="'+e+'" class="thumbxtag" href="'+t+'"><img src="'+v+'"/></a><strong><a href="'+t+'">'+e+'</a></strong><div class="info">'+(!0===a.options.ShowDate?'<span class="date"><i class="fa fa-calendar"></i><span class="dd">'+w+'</span> <span class="dm">'+z+'</span> <span class="dy">'+y+"</span></span>":"")+(!0===a.options.ShowComment?'<span class="comnum"><i class="fa fa-comments"></i><a href="'+t+'#comment-form">'+u+"</a></span>":"")+"</div><p "+
(!1===a.options.ShowDesc?"":'style="display:block"')+">"+f+"</p></div></li>"+(h[k]!==h[0]||"s"===a.options.postType||r.length?"":'<div class="recntright"><div class="box-wrap antiscroll-wrap"><div class="box"><div class="antiscroll-inner"><div class="box-inner"><ul>')+(h[k]!==h[q+1]||"s"===a.options.postType||r.length?"":"</ul></div></div></div></div>"+x+"</div>")}n.length?(a.$el.find(".recntright ul").append(g),a.$el.find(".box-wrap").antiscroll().data("antiscroll").refresh()):c("ul",a.$el).append(g);
if("s"===a.options.postType)b=c(d).parents(".widget").children("h2"),0!=a.options.tagName&&b.wrapInner('<a href="/search/label/'+encodeURIComponent(a.options.tagName)+'"/>'),t=a.$el.width(),b=300>t?1:450>t?2:700>t?3:4,t/=b,c(".rcbytag",a.$el).flexslider({animation:"slide",selector:".rcentpost > li",animationLoop:!0,itemWidth:t,minItems:1,move:b,mousewheel:!0,maxItems:3});else{var x=!1!==a.options.tagName?'<div class="morepostag"><a class="recntmore" title="'+a.options.MoreText+" "+a.options.tagName+
'" href="/search/label/'+encodeURIComponent(a.options.tagName)+"?&max-results="+a.options.MoreNumPost+'">'+a.options.MoreText+" "+a.options.tagName+"</a></div>":'<div class="morepostag rect"><a class="recntmore" title="'+a.options.LoadMoreText+'" href="#">'+a.options.LoadMoreText+"</a></div>";n.length||(a.$el.find(".recntright").append(x),a.$el.find(".box-wrap").antiscroll().data("antiscroll"),a.options.AjaxLoad||c(".morepostag.rect").hide());r.length+a.options.MaxPost>=b.feed.openSearch$totalResults.$t&&
a.$el.find(".morepostag").hide();a.$el.find(".morepostag a.recntmore").removeClass("loadingnya")}a.$el.removeClass(a.options.loadingClass)}else a.$el.html("<span>No result! Or Error Loading Feed</span>")};if(!0===a.options.Random)c.get((""===a.options.blogURL?window.location.protocol+"//"+window.location.host:a.options.blogURL)+"/feeds/posts/default"+(!1===a.options.tagName?"":"/-/"+a.options.tagName)+"?max-results=0&orderby=published&alt=json-in-script",function(b){b=a.options.MaxPost>b.feed.openSearch$totalResults.$t?
1:getRandomInt(1,b.feed.openSearch$totalResults.$t-a.options.MaxPost);c.get((""===a.options.blogURL?window.location.protocol+"//"+window.location.host:a.options.blogURL)+"/feeds/posts/default"+(!1===a.options.tagName?"":"/-/"+a.options.tagName)+"?max-results="+a.options.MaxPost+"&orderby=published&start-index="+b+"&alt=json-in-script",e,"jsonp")},"jsonp");else{var g=c.get((""===a.options.blogURL?window.location.protocol+"//"+window.location.host:a.options.blogURL)+"/feeds/posts/default"+(!1===a.options.tagName?
"":"/-/"+a.options.tagName)+"?max-results="+a.options.MaxPost+"&orderby=published&alt=json-in-script",e,"jsonp");c.when(g).done(function(){a.options.AjaxLoad&&a.$el.find(".morepostag a.recntmore").click(function(){a.$el.find(".morepostag a.recntmore").addClass("loadingnya");var b=a.$el.find("ul li").length+1;c.get((""===a.options.blogURL?window.location.protocol+"//"+window.location.host:a.options.blogURL)+"/feeds/posts/default"+(!1===a.options.tagName?"":"/-/"+a.options.tagName)+"?max-results="+
a.options.MaxPost+"&orderby=published&start-index="+b+"&alt=json-in-script",e,"jsonp");return!1})})}};a.init()};c.RecentPostbyTag.defaultOptions={blogURL:"",MaxPost:5,FirstImageSize:"s220-p",ImageSize:"s80-p",ShowDesc:!1,ShowDate:!0,ShowComment:!0,Random:!1,Summarylength:100,MoreText:"View All About",LoadMoreText:"Load More Post",MoreNumPost:6,AjaxLoad:!0,postType:"v",loadingClass:"loadingxx",pBlank:"https://1.bp.blogspot.com/-htG7vy9vIAA/Tp0KrMUdoWI/AAAAAAAABAU/e7XkFtErqsU/s72-c/grey.gif",MonthNames:"\u064a\u0646\u0627\u064a\u0631 \u0641\u0628\u0631\u0627\u064a\u0631 \u0645\u0627\u0631\u0633 \u0623\u0628\u0631\u064a\u0644 \u0645\u0627\u064a\u0648 \u064a\u0648\u0646\u064a\u0648 \u064a\u0648\u0644\u064a\u0648 \u0623\u063a\u0633\u0637\u0633 \u0633\u0628\u062a\u0645\u0628\u0631 \u0623\u0643\u062a\u0648\u0628\u0631 \u0646\u0648\u0641\u0645\u0628\u0631 \u062f\u064a\u0633\u0645\u0628\u0631".split(" "),
tagName:!1};c.fn.RecentPostbyTag=function(d){return this.each(function(){new c.RecentPostbyTag(this,d)})}})(jQuery);
function manualfeaturedPost(c){var d=c("#manualslide1"),b=d.children(".Image");0<b.length&&d.append('<div id="manualslidenya"><div class="featuredpost"><ul class="featpost"></ul></div></div>');b.each(function(){var a=c(this),b=a.find("h2").text(),d=a.find(".widget-content img").attr("src"),h=a.find(".widget-content a").attr("href");a=a.find(".caption").text();c("<li/>").append('<a title="'+b+'" class="feathumb" href="'+h+'"><img src="'+d+'"/></a><div class="labeltext"><strong class="titlex"><a href="'+
h+'">'+b+"</a></strong><p>"+a+"</p></div>").appendTo("#manualslide1 ul.featpost");c(this).remove()});0<b.length&&c("#manualslide1 .featuredpost").flexslider({animation:"slide",selector:".featpost > li",animationLoop:!0,mousewheel:!0,prevText:"<i></i>",nextText:"<i></i>",before:function(){c("#manualslidenya").find(".labeltext").stop().animate({right:-600,opacity:0},1E3)},after:function(){c("#manualslidenya").find(".labeltext").stop().animate({right:0,opacity:1},1E3)}})};